apiVersion: platform.acme.co/v1alpha1
kind: XNodePool
metadata:
  name: nodepool1
  annotations:
    render.crossplane.io/composition-path: apis/primitives/XNodepool/composition.yaml
    render.crossplane.io/function-path: examples/functions.yaml
spec:
  parameters:
    nodeConfig:
    - machineType: "e2-medium"
      preemptible: true
      nodeCount: 1
      serviceAccountRef: {}
      clusterRef: {}
