apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusters.platform.acme.co
spec:
  group: platform.acme.co
  names:
    kind: XCluster
    plural: xclusters
  claimNames:
    kind: Cluster
    plural: clusters
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            description: |
              The specification for how this cluster should be
              deployed.
            properties:
              parameters:
                type: object
                description: |
                  The parameters indicating how this cluster should
                  be configured.
                properties:
                  initialNodeCount:
                    type: number
                    description: |
                      The number of nodes for this cluster.
                  networkRef:
                    type: object
                    description: |
                      A reference to the network associated with this cluster.
                    properties:
                      name:
                        type: string
                        description: |
                          The name of the network associated with this cluster.
                  subnetworkRef:
                    type: object
                    description: |
                      A reference to the subnetwork associated with this cluster.
                    properties:
                      name:
                        type: string
                        description: |
                          The name of the subnetwork associated with this cluster.
                  project:
                    type: string
                    description: |
                      The cloud project this cluster should be created in.
                  location:
                    type: string
                    description: |
                      The geographic region in which this cluster
                      should be deployed.
                required:
                  - project
                  - networkRef
                  - location
            required:
              - parameters