apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xcompositeclusters.platform.acme.co
spec:
  compositeTypeRef:
    apiVersion: platform.acme.co/v1alpha1
    kind: XCompositeCluster
  mode: Pipeline
  pipeline:
    - step: compose
      functionRef:
        name: crossplane-contrib-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
        - name: cluster-nop
          base:
            apiVersion: platform.acme.co/v1alpha1
            kind: XCluster
            spec:
              parameters:
                project: "acme-project"
          patches:
          - type: FromCompositeFieldPath
            fromFieldPath: "metadata.name"
            toFieldPath: "metadata.name"
            transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-cluster"
          - type: FromCompositeFieldPath
            fromFieldPath: "spec.parameters.nodeCount"
            toFieldPath: "spec.parameters.initialNodeCount"
          - type: FromCompositeFieldPath
            fromFieldPath: "metadata.name"
            toFieldPath: "spec.parameters.networkRef.name"
            transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-net"
          - type: FromCompositeFieldPath
            fromFieldPath: "metadata.name"
            toFieldPath: "spec.parameters.subnetworkRef.name"
            transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-subnet"
          - type: FromCompositeFieldPath
            fromFieldPath: "spec.parameters.location"
            toFieldPath: "spec.parameters.location"
        - name: sa-nop
          base:
            apiVersion: platform.acme.co/v1alpha1
            kind: XServiceAccount
            spec:
              parameters: {}
          patches:
          - type: FromCompositeFieldPath
            fromFieldPath: "metadata.name"
            toFieldPath: "metadata.name"
            transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-sa"
          - type: FromCompositeFieldPath
            fromFieldPath: "metadata.name"
            toFieldPath: "spec.parameters.displayName"
            transforms:
            - type: string
              string:
                type: Format
                fmt: "%s service account"
        - name: nodepool-nop
          base:
            apiVersion: platform.acme.co/v1alpha1
            kind: XNodePool
            spec:
              parameters:
                nodeConfig: 
                - preemptible: True
          patches:
          - type: FromCompositeFieldPath
            fromFieldPath: "metadata.name"
            toFieldPath: "metadata.name"
            transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-nodepool"
          - type: FromCompositeFieldPath
            fromFieldPath: "spec.parameters.nodeCount"
            toFieldPath: "spec.parameters.nodeConfig[0].nodeCount"
          - type: FromCompositeFieldPath
            fromFieldPath: "spec.parameters.size"
            toFieldPath: "spec.parameters.nodeConfig[0].machineType"
          - type: FromCompositeFieldPath
            fromFieldPath: "metadata.name"
            toFieldPath: "spec.parameters.nodeConfig[0].serviceAccountRef.name"
            transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-sa"
          - type: FromCompositeFieldPath
            fromFieldPath: "metadata.name"
            toFieldPath: "spec.parameters.nodeConfig[0].clusterRef.name"
            transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-cluster"
        - name: network-nop
          base:
            apiVersion: platform.acme.co/v1alpha1
            kind: XNetwork
            spec:
              parameters:
                autoCreateSubnetworks: True
                routingMode: "GLOBAL"
          patches:
          - type: FromCompositeFieldPath
            fromFieldPath: "metadata.name"
            toFieldPath: "metadata.name"
            transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-net"
        - name: subnet-nop
          base:
            apiVersion: platform.acme.co/v1alpha1
            kind: XSubnetwork
            spec:
              parameters:
                ipCidrRange: "10.2.0.0/16"
                secondaryIpRange:
                - ipCidrRange: "192.168.10.0/24"
                  rangeName: "test-secondary-range-update1"
          patches:
          - type: FromCompositeFieldPath
            fromFieldPath: "metadata.name"
            toFieldPath: "metadata.name"
            transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-subnet"
          - type: FromCompositeFieldPath
            fromFieldPath: "metadata.name"
            toFieldPath: "spec.parameters.networkRef.name"
            transforms:
            - type: string
              string:
                type: Format
                fmt: "%s-net"
          - type: FromCompositeFieldPath
            fromFieldPath: "spec.parameters.location"
            toFieldPath: "spec.parameters.region"