apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xaccountscaffolds.platform.acme.co
spec:
  group: platform.acme.co
  names:
    kind: XAccountScaffold
    plural: xaccountscaffolds
  claimNames:
    kind: AccountScaffold
    plural: accountscaffolds
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: |
                The specification for how this account should be
                deployed.
              properties:
                parameters:
                  type: object
                  description: |
                    The parameters indicating how this account should
                    be configured.
                  properties:
                    name:
                      type: string
                      description: |
                        The name of the account to be scaffolded.
                  required:
                    - name
              required:
                - parameters
