apiVersion: platform.acme.co/v1alpha1
kind: ServiceAccount
metadata:
  name: serviceaccount1
  namespace: default
  annotations:
    render.crossplane.io/composition-path: apis/primitives/serviceaccount/composition.yaml
    render.crossplane.io/function-path: examples/functions.yaml
spec:
  parameters:
    displayName: "service account 1"
