apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-getting-started
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/configuration-getting-started
    meta.crossplane.io/license: Apache-2.0
spec:
  crossplane:
    version: ">=v1.15.2"
  dependsOn:
    - provider: xpkg.upbound.io/crossplane-contrib/provider-nop
      # renovate: datasource=github-releases depName=crossplane-contrib/provider-nop
      version: "v0.2.1"
    - function: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform
      # renovate: datasource=github-releases depName=crossplane-contrib/function-patch-and-transform
      version: "v0.6.0"
