apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xnodepools.platform.acme.co
spec:
  compositeTypeRef:
    apiVersion: platform.acme.co/v1alpha1
    kind: XNodePool
  mode: Pipeline
  pipeline:
  - step: compose
    functionRef:
      name: function-kcl
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLRun
      metadata:
        name: compose-nodepool
      spec:
        target: Resources
        params:
          name: "input-instance"
        source: |
          oxr = option("params").oxr
          items = [{
              apiVersion: "nop.crossplane.io/v1alpha1"
              kind: "NopResource"
              metadata.name = oxr.metadata.name
              spec.forProvider = {
                conditionAfter = [{
                  conditionStatus: "True"
                  conditionType: "Ready"
                  time: "5s"
                }]
                fields = {
                  nodeConfig: oxr.spec.parameters.nodeConfig
                }    
              }
          }]
  - step: automatically-detect-ready-composed-resources
    functionRef:
      name: function-auto-ready